from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="skt-ai-labs-adk",
    version="1.0.0",
    author="SKT-AI-LABS",
    author_email="dev@sktailabs.com",
    description="🔥 SKT-AI-LABS Agent Development Kit - Production-grade AI Agents",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/skt-ai-labs/skt-ai-labs-adk",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
    python_requires=">=3.10",
    install_requires=[
        "langchain>=0.3.0",
        "langgraph>=0.2.0",
        "langchain-community>=0.3.0",
        "openai>=1.0.0",
        "google-generativeai>=0.8.0",
        "groq>=0.9.0",
        "tavily-python>=0.5.0",
        "duckduckgo-search>=6.0.0",
        "beautifulsoup4>=4.12.0",
        "playwright>=1.40.0",
        "crawl4ai>=0.4.0",
        "requests>=2.31.0",
        "aiohttp>=3.9.0",
        "pydantic>=2.5.0",
        "sqlalchemy>=2.0.0",
        "pgvector>=0.2.0",
        "sentence-transformers>=3.0.0",
        "chromadb>=0.5.0",
        "faiss-cpu>=1.8.0",
        "redis>=5.0.0",
        "fastapi>=0.115.0",
        "uvicorn>=0.30.0",
        "websockets>=12.0",
        "streamlit>=1.40.0",
        "gradio>=5.0.0",
        "python-dotenv>=1.0.0",
        "structlog>=24.0.0",
        "tenacity>=8.2.0",
        "httpx>=0.27.0",
        "markdown>=3.6.0",
        "jinja2>=3.1.0",
        "typer>=0.12.0",
        "rich>=13.0.0",
        "psutil>=5.9.0",
        "numpy>=1.26.0",
        "pandas>=2.1.0",
    ],
    extras_require={
        "dev": ["pytest>=8.0", "pytest-asyncio>=0.23", "black>=24.0", "ruff>=0.4.0"],
        "browser": ["playwright>=1.40", "selenium>=4.15"],
        "gpu": ["faiss-gpu>=1.8.0", "torch>=2.2.0"],
    },
    entry_points={
        "console_scripts": [
            "skt-adk=skt_ai_labs.cli.main:main",
            "skt-agent=skt_ai_labs.cli.agent_cli:run_agent",
        ],
    },
    include_package_data=True,
    zip_safe=False,
)
